/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javadatabase;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.List;
/**
 *
 * @author ADVAN
 */
public class DatabaseOop extends javax.swing.JFrame {

private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DatabaseOop.class.getName());
private mahasiswa selectedMahasiswa = null;

    public DatabaseOop() {
        initComponents();
        loadData();
        setLocationRelativeTo(null);
        setTitle("Aplikasi CRUD Sederhana");

        tblMahasiswa.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int row = tblMahasiswa.getSelectedRow();
                if (row >= 0) {
                    int id = Integer.parseInt(tblMahasiswa.getModel().getValueAt(row, 0).toString());
                    String nim = tblMahasiswa.getModel().getValueAt(row, 1).toString();
                    String nama = tblMahasiswa.getModel().getValueAt(row, 2).toString();
 
                    selectedMahasiswa = new mahasiswa(id, nim, nama);
                    txtNama.setText(nama);
                    txtNIM.setText(nim);
                }
            }
        });
    }
    private void loadData() {
        DefaultTableModel model = new DefaultTableModel(new Object[]{"ID", "NIM", "Nama"}, 0);
        List<mahasiswa> list = JavaDatabaseOop.getAllmahasiswa();
        
        for (mahasiswa m : list) {
            model.addRow(new Object[]{m.id, m.nim, m.nama});
        }       
        tblMahasiswa.setModel(model);
        tblMahasiswa.moveColumn(2, 0); 
        tblMahasiswa.moveColumn(2, 1); 
        
        tblMahasiswa.getColumnModel().getColumn(2).setMinWidth(0);
        tblMahasiswa.getColumnModel().getColumn(2).setMaxWidth(0);
        tblMahasiswa.getColumnModel().getColumn(2).setWidth(0);
    }

    private void clearForm() {
        txtNama.setText("");
        txtNIM.setText("");
        selectedMahasiswa = null;
        
        btnTambah.setEnabled(true);
        tblMahasiswa.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMahasiswa = new javax.swing.JLabel();
        lblNIM = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        txtNIM = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMahasiswa = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnUploudCSv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblMahasiswa.setText("Tabel Mahasiswa");

        lblNIM.setText("NIM");

        lblNama.setText("Nama");

        txtNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNIMActionPerformed(evt);
            }
        });

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        tblMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nama", "NIM"
            }
        ));
        jScrollPane1.setViewportView(tblMahasiswa);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnUploudCSv.setText("UnggahCSV");
        btnUploudCSv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploudCSvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(55, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(189, 189, 189)
                                .addComponent(lblMahasiswa))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(btnUploudCSv)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnTambah)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnEdit)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnHapus))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(59, 59, 59)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNama, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(39, 39, 39)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                                        .addComponent(txtNIM)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblMahasiswa)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNIM)
                    .addComponent(txtNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus)
                    .addComponent(btnUploudCSv))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        try {
            if (txtNama.getText().isEmpty() || txtNIM.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "NIM dan Nama harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String nim = txtNIM.getText();    
            String nama = txtNama.getText();
            mahasiswa m = new mahasiswa(nim, nama);            
            JavaDatabaseOop.insert(m);              
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
            loadData();  
            clearForm();  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error tambah: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {
            if (selectedMahasiswa == null) {
                JOptionPane.showMessageDialog(this, "Pilih tabel terlebih dahulu!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String nim = txtNIM.getText();    
            String nama = txtNama.getText();
            mahasiswa m = new mahasiswa(selectedMahasiswa.id, nim, nama);            
            JavaDatabaseOop.edit(m);              
            JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
            loadData();
            clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error update: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
            if (selectedMahasiswa == null) {
                JOptionPane.showMessageDialog(this, "Pilih data dari tabel yang akan dihapus!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }          
            int id = selectedMahasiswa.id;
            int a = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data: " + selectedMahasiswa.nama + "?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (a == JOptionPane.YES_OPTION) {
                JavaDatabaseOop.hapus(id);
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                loadData();
                clearForm();
            }            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error delete: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNIMActionPerformed

    private void btnUploudCSvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploudCSvActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Pilih File CSV");
        fileChooser.setFileFilter(new FileNameExtensionFilter("File CSV (*.csv)", "csv"));
        
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String line;
            int count = 0;
            
            try (BufferedReader br = new BufferedReader(new FileReader(selectedFile))) {
                br.readLine();  
                while ((line = br.readLine()) != null) {
                    String[] data = line.split(",");
                    
                    if (data.length >= 2) {  
                        try {
                            String nama = data[0].trim();
                            String nim = data[1].trim();
                            mahasiswa m = new mahasiswa(nim, nama);
                            JavaDatabaseOop.insert(m);
                            count++;
                        } catch (Exception e) { 
                            logger.warning("Error memasukkan baris: " + line + " - " + e.getMessage());
                        }
                    } else {
                        logger.warning("Melewatkan baris (format tidak valid, perlu 2 kolom): " + line);
                    }
                }             
                JOptionPane.showMessageDialog(this, count + " data berhasil diunggah dari CSV!");
                loadData();             
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error membaca file CSV: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnUploudCSvActionPerformed
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) { 
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(DatabaseOop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new DatabaseOop().setVisible(true));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUploudCSv;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMahasiswa;
    private javax.swing.JLabel lblNIM;
    private javax.swing.JLabel lblNama;
    private javax.swing.JTable tblMahasiswa;
    private javax.swing.JTextField txtNIM;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
