/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javadatabase;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.List;
import java.text.NumberFormat; 
import java.util.Locale;
/**
 *
 * @author ADVAN
 */
public class DatabaseOop extends javax.swing.JFrame {

private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DatabaseOop.class.getName());
private mahasiswa selectedMahasiswa = null;

    public DatabaseOop() {
        initComponents();
        loadData();
        setLocationRelativeTo(null);
        setTitle("Aplikasi CRUD Sederhana");
        cmbJenisMahasiswa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reguler", "Beasiswa", "Internasional" }));
        final NumberFormat currencyFormat = NumberFormat.getCurrencyInstance(new Locale("in", "ID")); 
        
        tblMahasiswa.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int row = tblMahasiswa.getSelectedRow();
                if (row >= 0) {
                    int id = Integer.parseInt(tblMahasiswa.getModel().getValueAt(row, 0).toString());
                    String nim = tblMahasiswa.getModel().getValueAt(row, 1).toString();
                    String nama = tblMahasiswa.getModel().getValueAt(row, 2).toString();
                    String jenis = tblMahasiswa.getModel().getValueAt(row, 3).toString(); 
                    int sks = Integer.parseInt(tblMahasiswa.getModel().getValueAt(row, 4).toString()); 
                    double biaya = Double.parseDouble(tblMahasiswa.getModel().getValueAt(row, 5).toString()); 
                    
                    selectedMahasiswa = JavaDatabaseOop.createMahasiswaObject(id, nim, nama, jenis, sks);
                    
                    txtNama.setText(nama);
                    txtNIM.setText(nim);
                    cmbJenisMahasiswa.setSelectedItem(jenis);
                    txtSKS.setText(String.valueOf(sks)); 
                    
                    jLabel3.setText(currencyFormat.format(biaya));
                }
            }
        });
    }
    private void loadData() {
        DefaultTableModel model = new DefaultTableModel(new Object[]{"ID", "NIM", "Nama", "Jenis", "SKS", "Biaya Kuliah"}, 0);
        List<mahasiswa> list = JavaDatabaseOop.getAllmahasiswa();
        
        for (mahasiswa m : list) {
            model.addRow(new Object[]{m.id, m.nim, m.nama, m.jenisMahasiswa, m.jumlahSKS, m.getBiayaKuliah()});
        }        
        tblMahasiswa.setModel(model);
        tblMahasiswa.getColumnModel().getColumn(0).setMinWidth(0);
        tblMahasiswa.getColumnModel().getColumn(0).setMaxWidth(0);
        tblMahasiswa.getColumnModel().getColumn(0).setWidth(0);
    }
    private void clearForm() {
        txtNama.setText("");
        txtNIM.setText("");
        txtSKS.setText(""); 
        cmbJenisMahasiswa.setSelectedIndex(0); 
        jLabel3.setText("Rp 0,00"); 
        selectedMahasiswa = null;
        btnTambah.setEnabled(true);
        tblMahasiswa.clearSelection();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMahasiswa = new javax.swing.JLabel();
        lblNIM = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        txtNIM = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMahasiswa = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnUploudCSv = new javax.swing.JButton();
        lblJenisMahasiswa = new javax.swing.JLabel();
        cmbJenisMahasiswa = new javax.swing.JComboBox<>();
        lblJumlahSKS = new javax.swing.JLabel();
        txtSKS = new javax.swing.JTextField();
        lblBiaya = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblMahasiswa.setText("Tabel Mahasiswa");

        lblNIM.setText("NIM");

        lblNama.setText("Nama");

        txtNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNIMActionPerformed(evt);
            }
        });

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        tblMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama", "NIM", "Jenis", "SKS", "Biaya"
            }
        ));
        jScrollPane1.setViewportView(tblMahasiswa);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnUploudCSv.setText("UnggahCSV");
        btnUploudCSv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploudCSvActionPerformed(evt);
            }
        });

        lblJenisMahasiswa.setText("Jenis Mahasiswa");

        cmbJenisMahasiswa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblJumlahSKS.setText("Jumlah SKS");

        lblBiaya.setText("Biaya");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(lblMahasiswa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUploudCSv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnHapus))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNama, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNIM, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                                    .addComponent(txtNama)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblJumlahSKS, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblJenisMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbJenisMahasiswa, 0, 331, Short.MAX_VALUE)
                                    .addComponent(txtSKS)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblMahasiswa)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNIM)
                    .addComponent(txtNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJenisMahasiswa)
                    .addComponent(cmbJenisMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJumlahSKS)
                    .addComponent(txtSKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBiaya)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(btnEdit)
                    .addComponent(btnTambah)
                    .addComponent(btnUploudCSv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        try {
            if (txtNama.getText().isEmpty() || txtNIM.getText().isEmpty() || txtSKS.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "NIM, Nama, dan SKS harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String nim = txtNIM.getText();    
            String nama = txtNama.getText();
            String jenis = cmbJenisMahasiswa.getSelectedItem().toString(); 
            int sks = Integer.parseInt(txtSKS.getText()); 
            
            int tahun = java.time.Year.now().getValue();
            mahasiswa m = JavaDatabaseOop.createMahasiswaObject(nim, nama, jenis, sks);
            
            JavaDatabaseOop.insert(m);              
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
            loadData();  
            clearForm();  
        } catch (NumberFormatException e) {
             JOptionPane.showMessageDialog(this, "SKS harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error tambah: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {
            if (selectedMahasiswa == null) {
                JOptionPane.showMessageDialog(this, "Pilih tabel terlebih dahulu!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (txtNama.getText().isEmpty() || txtNIM.getText().isEmpty() || txtSKS.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "NIM, Nama, dan SKS harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String nim = txtNIM.getText();    
            String nama = txtNama.getText();
            String jenis = cmbJenisMahasiswa.getSelectedItem().toString();
            int sks = Integer.parseInt(txtSKS.getText());
         
            mahasiswa m = JavaDatabaseOop.createMahasiswaObject(selectedMahasiswa.id, nim, nama, jenis, sks);            
            
            JavaDatabaseOop.edit(m);               
            JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
            loadData();
            clearForm();
            
        } catch (NumberFormatException e) {
             JOptionPane.showMessageDialog(this, "SKS harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error update: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
            if (selectedMahasiswa == null) {
                JOptionPane.showMessageDialog(this, "Pilih data dari tabel yang akan dihapus!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }            
            int id = selectedMahasiswa.id;
            
            int a = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data: " + selectedMahasiswa.nama + "?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (a == JOptionPane.YES_OPTION) {
                JavaDatabaseOop.hapus(id); 
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                loadData();
                clearForm();
            }            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error delete: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNIMActionPerformed

    private void btnUploudCSvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploudCSvActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Pilih File CSV");
        fileChooser.setFileFilter(new FileNameExtensionFilter("File CSV (*.csv)", "csv"));
        
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String line;
            int count = 0;
            
            try (BufferedReader br = new BufferedReader(new FileReader(selectedFile))) {
                br.readLine();  
                while ((line = br.readLine()) != null) {
                    String[] data = line.split(",");
                    if (data.length >= 5) { 
                        try {
                            String nim = data[0].trim();
                            String nama = data[1].trim();
                            String jenis = data[2].trim(); 
                            int sks = Integer.parseInt(data[3].trim()); 
                            
                            mahasiswa m = JavaDatabaseOop.createMahasiswaObject(nim, nama, jenis, sks);
                            JavaDatabaseOop.insert(m);
                            count++;
                        } catch (NumberFormatException e) {
                            logger.warning("Melewatkan baris (angka SKS/Tahun tidak valid): " + line);
                        } catch (Exception e) {
                            logger.warning("Error memasukkan baris: " + line + " - " + e.getMessage());
                        }
                    } else {
                        logger.warning("Melewatkan baris (format tidak valid, kurang dari 5 kolom): " + line);
                    }
                }               
                JOptionPane.showMessageDialog(this, count + " data berhasil diunggah dari CSV!");
                loadData();               
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error membaca file CSV: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnUploudCSvActionPerformed
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) { 
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(DatabaseOop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new DatabaseOop().setVisible(true));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUploudCSv;
    private javax.swing.JComboBox<String> cmbJenisMahasiswa;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBiaya;
    private javax.swing.JLabel lblJenisMahasiswa;
    private javax.swing.JLabel lblJumlahSKS;
    private javax.swing.JLabel lblMahasiswa;
    private javax.swing.JLabel lblNIM;
    private javax.swing.JLabel lblNama;
    private javax.swing.JTable tblMahasiswa;
    private javax.swing.JTextField txtNIM;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtSKS;
    // End of variables declaration//GEN-END:variables
}
